/*2.mailing_system*/

BEGIN;

CREATE TABLE IF NOT EXISTS "human_has_message" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "human_id" integer NOT NULL REFERENCES "human"("id")  ON DELETE CASCADE,
  "cat_id" integer NOT NULL REFERENCES "cat" ("id")  ON DELETE CASCADE,
  "message" TEXT NOT NULL,  
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "cat_has_message" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "cat_id" integer NOT NULL REFERENCES "cat"("id")  ON DELETE CASCADE,
  "human_id" integer NOT NULL REFERENCES "human" ("id")  ON DELETE CASCADE,
  "message" TEXT NOT NULL, 
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

COMMIT;



/* jwt_log */


BEGIN;

CREATE TABLE IF NOT EXISTS "user_tokens" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "account_id" integer NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "content" TEXT NOT NULL,  
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

COMMIT;